name: Greetings

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet first-time contributors
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            👋 **Welcome!**
            
            Thank you for opening your first issue in this project. We appreciate your contribution!
            
            Please be sure to review our [Code of Conduct](../blob/main/CODE_OF_CONDUCT.md) and [Security Policy](../blob/main/SECURITY.md).
          pr-message: |
            👋 **Welcome!**
            
            Thank you for submitting your first pull request to this project. We appreciate your effort and contribution!
            
            Please be sure to review our [Code of Conduct](../blob/main/CODE_OF_CONDUCT.md) and [Security Policy](../blob/main/SECURITY.md). 